### ISSUE TITLE
Vue generator breaks if schema's name has '-' in declaration

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#99]
So, here how to reproduce the scenario, I am sharing the schema sample too. In the example below the event's name is ``input-box`` so when the generator runs it's breaking and when I remove the ``-`` from the name the component is generated successfully.

Possible Solutions
1. Configure the ``schema`` not to accept ``-`` in the name if it has an event. (which is a little tricky and I am not sure how we can achieve).
2. Change the logic that is being currently used for generating Event Handler names.

```
           {
                "type": "text",
                "name": "input-box",
                "events": {
                    "onClick": [
                        {
                            "type": "stateChange",
                            "modifies": "toggleComponent",
                            "newState": true
                        }
                    ]
                }
            }
```

~~~
{ SyntaxError: Unexpected token, expected "," (11:16)
   9 | 
  10 |   methods: {
> 11 |     handleInput-boxOnClick() {
     |                ^
  12 |       this.toggleComponent = true;
  13 |     }
  14 | 
    at t (/Users/a1290641/Documents/personal/teleport-code-generators/node_modules/prettier/parser-babylon.js:1:264)
    at Object.parse (/Users/a1290641/Documents/personal/teleport-code-generators/node_modules/prettier/parser-babylon.js:1:208428
)
    at Object.parse$2 [as parse] (/Users/a1290641/Documents/personal/teleport-code-generators/node_modules/prettier/standalone.js:12953:19)
    at coreFormat (/Users/a1290641/Documents/personal/teleport-code-generators/node_modules/prettier/standalone.js:16180:23)
    at format (/Users/a1290641/Documents/personal/teleport-code-generators/node_modules/prettier/standalone.js:16441:73)
    at formatWithCursor (/Users/a1290641/Documents/personal/teleport-code-generators/node_modules/prettier/standalone.js:16457:12)
    at /Users/a1290641/Documents/personal/teleport-code-generators/node_modules/prettier/standalone.js:30711:15
    at Object.format (/Users/a1290641/Documents/personal/teleport-code-generators/node_modules/prettier/standalone.js:30719:12)
    at Object.exports.generator [as js] (/Users/a1290641/Documents/personal/teleport-code-generators/src/core/builder/generators/js-ast-to-code.ts:16:21)
    at Builder.generateByType (/Users/a1290641/Documents/personal/teleport-code-generators/src/core/builder/index.ts:82:33)
  loc: { start: { line: 11, column: 16 } },
~~~

**Comment by alexnm** [comment]
good catch. we need to be careful with what's valid in each framework we output code. We have a couple of functions for this in the `string-utils.ts` file.

either `sanitizeVariableName` or `stringToCamelCase` can be used in this case, I think

@allcontributors[bot] please add @JayaKrishnaNamburu for bug

**Comment by JayaKrishnaNamburu** [comment]
ok, will fix this one too when doing the Ternary Operations for Vue 👍
